# Generated by Django 5.2.10 on 2026-02-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_onboarding', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_genres', models.ManyToManyField(blank=True, to='games.genre')),
                ('preferred_platform', models.ManyToManyField(blank=True, to='games.platform')),
                ('preferred_player_perspective', models.ManyToManyField(blank=True, to='games.playerperspective')),
                ('preferred_themes', models.ManyToManyField(blank=True, to='games.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
