# Generated by Django 5.2.9 on 2026-02-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='completed_onbording',
            new_name='completed_onboarding',
        ),
    ]
