# Generated by Django 5.2.9 on 2026-01-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverallrating',
            name='rating_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_ratings', to='games.ratingtype'),
        ),
    ]
