# Generated by Django 5.2.9 on 2025-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rating/'),
        ),
    ]
