# Generated by Django 5.2.10 on 2026-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
