# Generated by Django 5.2.9 on 2026-01-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameoverallrating_rating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtype',
            name='category_rating_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
