# Generated by Django 5.2.11 on 2026-03-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_igdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='similar_games',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
    ]
