# Generated by Django 5.2.9 on 2025-12-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_rating_remove_game_play_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='released',
            field=models.DateField(auto_now=True),
        ),
    ]
