# Generated by Django 5.2.9 on 2025-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='released',
            field=models.DateField(),
        ),
    ]
