# Generated by Django 5.2.9 on 2026-01-14 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_ratingtype_category_rating_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecategoryrating',
            name='rating_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='games.ratingtype'),
        ),
    ]
