# Generated by Django 5.2.9 on 2026-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_igdbsyncstatus_game_igdb_id_game_igdb_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
