# Generated by Django 5.2.9 on 2026-01-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
