# Generated by Django 5.2.9 on 2025-12-23 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamestatus_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='image',
            field=models.FileField(upload_to='status_icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
