# Generated by Django 5.2.9 on 2025-12-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_gamestatus_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='audio_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='gameplay_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='overall_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='playability_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='story_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visual_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'game')},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('value', models.SmallIntegerField()),
                ('game_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='games.usergamerating')),
            ],
            options={
                'unique_together': {('game_rating', 'category')},
            },
        ),
    ]
