# Generated by Django 5.2.9 on 2025-12-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_audio_rating_game_gameplay_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='game_rating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
    ]
