# Generated by Django 5.2.9 on 2025-12-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_category_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ratings/')),
                ('weight', models.PositiveSmallIntegerField()),
                ('color', models.CharField(default='#000000', max_length=20)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='audio_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameplay_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playability_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='story_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visual_rating',
        ),
        migrations.AddField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingcategory'),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='rating_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingtype'),
        ),
        migrations.DeleteModel(
            name='UserGameRating',
        ),
        migrations.AlterUniqueTogether(
            name='gamerating',
            unique_together={('game', 'user', 'category')},
        ),
    ]
