# Generated by Django 5.2.9 on 2026-01-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_collection_company_franchise_gamemode_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='url',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='url',
        ),
        migrations.RemoveField(
            model_name='gamemode',
            name='url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='url',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='url',
        ),
        migrations.RemoveField(
            model_name='playerperspective',
            name='url',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='url',
        ),
    ]
