# Generated by Django 5.2.9 on 2026-01-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_collection_url_remove_franchise_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbsyncstatus',
            name='last_updated_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
