# Generated by Django 5.2.9 on 2025-12-28 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamerating_ratingcategory_ratingtype_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtype',
            name='image',
            field=models.ImageField(upload_to='ratings/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
