# Generated by Django 5.2.9 on 2026-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_igdbsyncstatus_last_updated_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='igdb_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
