# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_ratingtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtype',
            name='image',
            field=models.FileField(upload_to='ratings/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
