# Generated by Django 5.2.10 on 2026-02-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_company_igdb_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
