# Generated by Django 5.2.9 on 2025-12-30 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_ratingtype_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingcategory')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='games.game')),
                ('rating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='GameOverallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_ratings', to='games.game')),
                ('rating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='GameRating',
        ),
    ]
